### ISSUE TITLE
Getting parent and child node information from Monocle object

### ISSUE THREAD

**Issue by No2Ross** [canzarlab/Trajan#2]
Hello. 

I've been trying to use your method to test on some related trajectories but i'm not sure how you managed to extract the parent and child nodes in the trajectories from the monocle object to put into the tree file format. Any help on how you achieved this would be appreciated.

**Comment by laijen000** [comment]
hello @canzarlab @vanhoan310 I am also interested in using Trajan to align independent pseudotime trajectories obtained using Monocle2. It is still unclear to me how to generate the proper input files for Trajan from my Monocle2 output. I would greatly appreciate any help on how to format the Trajan inputs from monocle2 results. Thank you!

**Comment by canzarlab** [comment]
Please see the attached R script for how to process the monocle 2 graph. Then run the following to export data for Trajan input:
trajan <- Trajan(t1 = t1, t1_root = t1_root, t1_data = t1_data, t2 = t2, t2_root = t2_root, t2_data = t2_data, method = “pearson”)
Finally, simply run: 
./trajan t1.tree t1.map t2.tree t2.map distance_matrix.csv output_solution.csv 2 e 0 0 0.0001 2

For more information on how to use the Trajan object to export data into a format readable by our algorithm please check our description in Section “Example Workflow using Monocle generated Trajectories” and our example workflow in Rscripts/examples.R. Note that gene names must match between the two input data sets.

We hope this solves your problem. 

[github_issue_monocole.zip](https://github.com/canzarlab/Trajan/files/5952319/github_issue_monocole.zip)
